version: '3.7'
services:
  nextcloudpi:
    restart: unless-stopped
    image: ownyourbits/nextcloudpi
    command: "nextcloud.pi.chinour.fr"
    networks:
      - traefik_network
    volumes:
     - /cloud:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: nextcloudpi
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.nextcloud.entrypoints=web,websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.pi.chinour.fr`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
networks:
  traefik_network:
    external: true
